export const BudgetCategories = {
  housing: 'Housing',
  utilities: 'Utilities',
  groceries: 'Groceries',
  transportation: 'Transportation',
  insurance: 'Insurance',
  personalCare: 'Personal Care',
  entertainment: 'Entertainment',
  clothing: 'Clothing',
  education: 'Education',
  taxes: 'Taxes',
  children: 'Children',
  investments: 'Investments',
  vacation: 'Vacation',
  technology: 'Technology',
  online: 'Online',
  general: 'General',
  tools: 'Tools',
  charity: 'Charity',
  other: 'Other'
}
